### ISSUE TITLE
Cloudformation stack get error because of nodes 6.x

### ISSUE THREAD

**Issue by NickWoo33** [awslabs/aws-iot-certificate-vending-machine#9]
Hello,

Can anyone update the stack?

I tried to run the stack, it get error because lambda is nodejs 6.x, can anyone update the stack to meet the new version 10.x?

Thanks

**Comment by samhstein** [comment]
worked with updating the template, also make sure to run in n. virginia region for
access to the pubz bucket for the lamba function.

    "Runtime": "nodejs8.10",

**Comment by NickWoo33** [comment]
> worked with updating the template, also make sure to run in n. virginia region for
> access to the pubz bucket for the lamba function.
> 
> ```
> "Runtime": "nodejs8.10",
> ```

OK & Thx.

**Comment by davidsteed** [comment]
I tried nodejs10.x and this did not work got "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'app'",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'app'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:36:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:776:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
}
